name: 'Empty PR Actions'

description: 'GitHub Action that helps you make pull-requests look nice'

branding:
  icon: 'italic'
  color: 'red'

inputs:
  assignee:
    description: 'assignee'
    required: false
    default: ${{ github.event.issue.assignee.name }}

  email:
    description: 'email'
    required: false
    default: ${{ github.event.issue.assignee.email }}

  GITHUB_TOKEN:
    description: 'Github Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: run
      run: |
        cargo install ccase
        chmod +x "${GITHUB_WORKSPACE}/src/pull-request.sh"
        ${GITHUB_WORKSPACE}/src/pull-request.sh $args_str -r $GITHUB_REPOSITORY -n $number
      env:
        number: ${{ github.event.issue.number }}
        owner: ${{ inputs.assignee }}
        email: ${{ inputs.email }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
