name: Example Action

on:
  issues:
    types: [opened, closed, edited, reopened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run main
        id: main
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        #uses: chyccs/pull-request-typography@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
