name: on-pull-request-action

on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        run: |
          issue_url=$(gh issue create -t "test ${{ github.run_number }}" -b " " -R "$GITHUB_REPOSITORY")
          gh issue lock $issue_url -r "integration test"
          echo $issue_url
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Create PR when issue_comment event occured
      #   if: ${{ startsWith(github.event.comment.body, '@pr ') }}
      #   uses: ./
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      continue-on-error: true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
