name: on-pull-request-action

on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        run: |
          issue=$(gh issue create -t "test ${{ github.run_number }}" -b " " -R "$GITHUB_REPOSITORY")
          echo $issue
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Create Issue
      #   run: |
      #     issue=$(gh issue create -t "test" -b " " --label "test issue" -R "$GITHUB_REPOSITORY")
      #   shell: bash
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      continue-on-error: true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
