name: on-pull-request-action

on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-issue-job:
    runs-on: ubuntu-latest
    steps:
      - id: create-issue
        run: |
          issue_url=$(gh issue create -t "test ${{ github.run_number }}" -b " " -R "$GITHUB_REPOSITORY")
          #gh issue close $issue_url
          echo "issue_url=$issue_url" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create PR when issue_comment event occured
        uses: chyccs/empty-pr-actions@50-fix-add-integration-test-action
        with:
          issue_url: ${{ steps.create-issue.outputs.issue_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

