name: on-pull-request-action

on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        run: |
          issue=$(gh issue create -a "@me" -t "test" -b " " -R "$GITHUB_REPOSITORY")
        shell: bash

  add_assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        continue-on-error: true

  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      continue-on-error: true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
